…

diff --git a/etc/ci/update-wpt-checkout b/etc/ci/update-wpt-checkout
--- a/etc/ci/update-wpt-checkout
+++ b/etc/ci/update-wpt-checkout
@@ -31,28 +31,28 @@ function latest_git_commit() {
 function unsafe_pull_from_upstream() {
     git checkout -b "${1}" || return 1
 
-    OLD_COMMIT=$(latest_git_commit)
+#    OLD_COMMIT=$(latest_git_commit)
 
-    # Fetch all changes from upstream WPT and automatically transpose them
-    # into a single servo commit.
-    ./mach update-wpt --sync --no-upstream --patch || return 2
+#    # Fetch all changes from upstream WPT and automatically transpose them
+#    # into a single servo commit.
+#    ./mach update-wpt --sync --no-upstream --patch || return 2
 
-    # If there was no new commit created, there are no changes that need syncing.
-    # Skip the remaining steps.
-    if [[ "$(latest_git_commit)" == "${OLD_COMMIT}" ]]; then
-        return 255
-    fi
+#    # If there was no new commit created, there are no changes that need syncing.
+#    # Skip the remaining steps.
+#    if [[ "$(latest_git_commit)" == "${OLD_COMMIT}" ]]; then
+#        return 255
+#    fi
 
-    # Update the manifest to include the new changes.
-    ./mach update-manifest || return 3
-    # Update the manifest again to reach a fixed state (https://github.com/servo/servo/issues/22275).
-    ./mach update-manifest || return 4
+#    # Update the manifest to include the new changes.
+#    ./mach update-manifest || return 3
+#    # Update the manifest again to reach a fixed state (https://github.com/servo/servo/issues/22275).
+#    ./mach update-manifest || return 4
 
-    # Clean up any now-unused test results.
-    (python3 etc/unused_wpt_results.py | xargs rm -rfv) || return 5
+#    # Clean up any now-unused test results.
+#    (python3 etc/unused_wpt_results.py | xargs rm -rfv) || return 5
 
-    # Amend the existing commit with the new changes from updating the manifest.
-    git commit -a --amend --no-edit || return 6
+#    # Amend the existing commit with the new changes from updating the manifest.
+#    git commit -a --amend --no-edit || return 6
 }
 
 # Remove all local traces of this sync operation.
@@ -86,7 +86,7 @@ function unsafe_update_metadata() {
     # Ensure any new directories or ini files are included in these changes.
     git add tests/wpt/metadata tests/wpt/mozilla/meta || return 2
     # Merge all changes with the existing commit.
-    git commit -a --amend --no-edit || return 3
+    git commit -a -m "Update WPT" || return 3
 }
 
 # Push the branch to a remote branch, then open a PR for the branch
@@ -122,7 +122,7 @@ function unsafe_open_pull_request() {
     BODY+="r? @servo-wpt-sync\n"
     cat <<EOF >prdata.json || return 4
 {
-  "title": "Sync WPT with upstream (${CURRENT_DATE})",
+  "title": "[Do not merge] Sync WPT with upstream (${CURRENT_DATE}), from Linux",
   "head": "${WPT_SYNC_USER}:${REMOTE_BRANCH_NAME}",
   "base": "master",
   "body": "${BODY}",
@@ -136,11 +136,11 @@ EOF
                             --data @prdata.json \
                             https://api.github.com/repos/servo/servo/pulls) || return 5
 
-    echo "${OPEN_PR_RESPONSE}" | \
-        jq '.review_comments_url' | \
-        sed 's/pulls/issues/' | \
-        xargs curl -H "Authorization: token ${WPT_SYNC_TOKEN}" \
-                   --data "{\"body\":\"@bors-servo r+\"}" || return 6
+#    echo "${OPEN_PR_RESPONSE}" | \
+#        jq '.review_comments_url' | \
+#        sed 's/pulls/issues/' | \
+#        xargs curl -H "Authorization: token ${WPT_SYNC_TOKEN}" \
+#                   --data "{\"body\":\"@bors-servo r+\"}" || return 6
 }
 
 function pull_from_upstream() {
