Combine PR and main workflow to test the GitHub merge queue

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -1,4 +1,4 @@
-name: Mac workflow
+name: Mac
 
 on:
   workflow_call:
@@ -36,125 +36,131 @@ env:
   CARGO_INCREMENTAL: 0
 
 jobs:
-  build-mac:
-    name: Build
-    runs-on: macos-12
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 2
-      - name: Run sccache-cache
-        uses: mozilla-actions/sccache-action@v0.0.3
-      - name: Bootstrap
-        run: |
-          python3 -m pip install --upgrade pip virtualenv
-          python3 ./mach bootstrap
-      - name: Release build
-        run: |
-          python3 ./mach build --release
-      - name: Smoketest
-        run: python3 ./mach smoketest
-      - name: Script tests
-        run: ./mach test-scripts
-      - name: Unit tests
-        if: ${{ inputs.unit-tests || github.ref_name == 'try-mac' }}
-        run: python3 ./mach test-unit --release
-      - name: Package
-        run: python3 ./mach package --release
-      - name: Package smoketest
-        run: ./etc/ci/macos_package_smoketest.sh target/release/servo-tech-demo.dmg
-      - name: Rename build timing
-        run: cp -r target/cargo-timings target/cargo-timings-macos
-      - name: Archive build timing
-        uses: actions/upload-artifact@v3
-        with:
-          name: cargo-timings
-          # Using a wildcard here ensures that the archive includes the path.
-          path: target/cargo-timings-*
-      - name: Upload package
-        uses: actions/upload-artifact@v3
-        with:
-          name: mac
-          path: target/release/servo-tech-demo.dmg
-      - name: Upload
-        if: ${{ inputs.upload }}
-        run: |
-          python3 ./mach upload-nightly mac --secret-from-environment \
-            --github-release-id ${{ inputs.github-release-id }}
-        env:
-          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
-          GITHUB_HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
-          NIGHTLY_REPO_TOKEN: ${{ secrets.NIGHTLY_REPO_TOKEN }}
-          NIGHTLY_REPO: ${{ github.repository_owner }}/servo-nightly-builds
-      - name: Package binary
-        run: gtar -czf target.tar.gz target/release/servo target/release/*.dylib resources
-      - name: Archive binary
-        uses: actions/upload-artifact@v3
-        with:
-          name: release-binary-macos
-          path: target.tar.gz
-
-  # mac-wpt:
-  #   name: Mac WPT Tests
-  #   runs-on: macos-12
-  #   needs: ["build-mac"]
-  #   env:
-  #     max_chunk_id: 20
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       chunk_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 2
-  #     - uses: actions/download-artifact@v3
-  #       with:
-  #         name: release-binary-macos
-  #     # TODO: Remove this step when the compatibility issue between mozjs and
-  #     #       Homebrew's Python 3.10 formula (servo/rust-mozjs#559) is fixed
-  #     - name: Select Python 3.9
-  #       run: |
-  #         brew install python@3.9
-  #         cd $(dirname $(which python3.9))
-  #         rm -f python3 pip3
-  #         ln -s python3.9 python3
-  #         ln -s pip3.9 pip3
-  #     - name: Prep test environment
-  #       run: |
-  #         gtar -xzf target.tar.gz
-  #         python3 -m pip install --upgrade pip virtualenv
-  #         brew bundle install --verbose --no-upgrade --file=etc/homebrew/Brewfile
-  #     - name: Smoketest
-  #       run: python3 ./mach smoketest
-  #     - name: Run tests
-  #       run: |
-  #         python3 ./mach test-wpt \
-  #           --release --processes $(sysctl -n hw.logicalcpu) --timeout-multiplier 8 \
-  #           --total-chunks ${{ env.max_chunk_id }} --this-chunk ${{ matrix.chunk_id }} \
-  #           --log-raw test-wpt.${{ matrix.chunk_id }}.log \
-  #           --filter-intermittents=filtered-wpt-summary.${{ matrix.chunk_id }}.log
-  #     - name: Archive logs
-  #       uses: actions/upload-artifact@v3
-  #       if: ${{ failure() }}
-  #       with:
-  #         name: wpt${{ matrix.chunk_id }}-logs-macos
-  #         path: |
-  #           test-wpt.${{ matrix.chunk_id }}.log
-  #           filtered-wpt-summary.${{ matrix.chunk_id }}.log
-
+#  build-mac:
+#    name: Mac Build
+#    runs-on: macos-12
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 2
+#      - name: Run sccache-cache
+#        uses: mozilla-actions/sccache-action@v0.0.3
+#      - name: Bootstrap
+#        run: |
+#          python3 -m pip install --upgrade pip virtualenv
+#          python3 ./mach bootstrap
+#      - name: Release build
+#        run: |
+#          python3 ./mach build --release
+#      - name: Smoketest
+#        run: python3 ./mach smoketest
+#      - name: Script tests
+#        run: ./mach test-scripts
+#      - name: Unit tests
+#        if: ${{ inputs.unit-tests || github.ref_name == 'try-mac' }}
+#        run: python3 ./mach test-unit --release
+#      - name: Package
+#        run: python3 ./mach package --release
+#      - name: Package smoketest
+#        run: ./etc/ci/macos_package_smoketest.sh target/release/servo-tech-demo.dmg
+#      - name: Rename build timing
+#        run: cp -r target/cargo-timings target/cargo-timings-macos
+#      - name: Archive build timing
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: cargo-timings
+#          # Using a wildcard here ensures that the archive includes the path.
+#          path: target/cargo-timings-*
+#      - name: Upload package
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: mac
+#          path: target/release/servo-tech-demo.dmg
+#      - name: Upload
+#        if: ${{ inputs.upload }}
+#        run: |
+#          python3 ./mach upload-nightly mac --secret-from-environment \
+#            --github-release-id ${{ inputs.github-release-id }}
+#        env:
+#          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
+#          GITHUB_HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
+#          NIGHTLY_REPO_TOKEN: ${{ secrets.NIGHTLY_REPO_TOKEN }}
+#          NIGHTLY_REPO: ${{ github.repository_owner }}/servo-nightly-builds
+#      - name: Package binary
+#        run: gtar -czf target.tar.gz target/release/servo target/release/*.dylib resources
+#      - name: Archive binary
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: release-binary-macos
+#          path: target.tar.gz
+#
+#  # mac-wpt:
+#  #   name: Mac WPT Tests
+#  #   runs-on: macos-12
+#  #   needs: ["build-mac"]
+#  #   env:
+#  #     max_chunk_id: 20
+#  #   strategy:
+#  #     fail-fast: false
+#  #     matrix:
+#  #       chunk_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
+#  #   steps:
+#  #     - uses: actions/checkout@v3
+#  #       with:
+#  #         fetch-depth: 2
+#  #     - uses: actions/download-artifact@v3
+#  #       with:
+#  #         name: release-binary-macos
+#  #     # TODO: Remove this step when the compatibility issue between mozjs and
+#  #     #       Homebrew's Python 3.10 formula (servo/rust-mozjs#559) is fixed
+#  #     - name: Select Python 3.9
+#  #       run: |
+#  #         brew install python@3.9
+#  #         cd $(dirname $(which python3.9))
+#  #         rm -f python3 pip3
+#  #         ln -s python3.9 python3
+#  #         ln -s pip3.9 pip3
+#  #     - name: Prep test environment
+#  #       run: |
+#  #         gtar -xzf target.tar.gz
+#  #         python3 -m pip install --upgrade pip virtualenv
+#  #         brew bundle install --verbose --no-upgrade --file=etc/homebrew/Brewfile
+#  #     - name: Smoketest
+#  #       run: python3 ./mach smoketest
+#  #     - name: Run tests
+#  #       run: |
+#  #         python3 ./mach test-wpt \
+#  #           --release --processes $(sysctl -n hw.logicalcpu) --timeout-multiplier 8 \
+#  #           --total-chunks ${{ env.max_chunk_id }} --this-chunk ${{ matrix.chunk_id }} \
+#  #           --log-raw test-wpt.${{ matrix.chunk_id }}.log \
+#  #           --filter-intermittents=filtered-wpt-summary.${{ matrix.chunk_id }}.log
+#  #     - name: Archive logs
+#  #       uses: actions/upload-artifact@v3
+#  #       if: ${{ failure() }}
+#  #       with:
+#  #         name: wpt${{ matrix.chunk_id }}-logs-macos
+#  #         path: |
+#  #           test-wpt.${{ matrix.chunk_id }}.log
+#  #           filtered-wpt-summary.${{ matrix.chunk_id }}.log
+#
+#  build_result:
+#    name: Mac Workflow
+#    runs-on: ubuntu-latest
+#    if: always()
+#    # needs all build to detect cancellation
+#    needs:
+#      - "build-mac"
+#
+#    steps:
+#      - name: Mark the job as successful
+#        run: exit 0
+#        if: ${{ !contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') }}
+#      - name: Mark the job as unsuccessful
+#        run: exit 1
+#        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
   build_result:
-    name: homu build finished
+    name: Result
     runs-on: ubuntu-latest
-    if: always()
-    # needs all build to detect cancellation
-    needs:
-      - "build-mac"
-
     steps:
-      - name: Mark the job as successful
-        run: exit 0
-        if: ${{ !contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') }}
-      - name: Mark the job as unsuccessful
-        run: exit 1
-        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
+      - name: Print workflow inputs
+        run: echo unit='${{ inputs.unit-tests }}' wpt='${{ inputs.wpt }}' layout='${{ inputs.layout }}'
