Add validation step
This will make it easier to identify missing artifact IDs if the problem occurs again.

Signed-off-by: Jonathan Schwender <schwenderjonathan@gmail.com>

diff --git a/.github/workflows/upload_release.yml b/.github/workflows/upload_release.yml
--- a/.github/workflows/upload_release.yml
+++ b/.github/workflows/upload_release.yml
@@ -39,6 +39,15 @@ jobs:
           fetch-depth: '1'
       - name: Setup Python
         uses: ./.github/actions/setup-python
+      - name: Validate artifact IDs
+        run: |
+          if [[ -z "${{ inputs.artifact_ids }}" ]]; then
+            echo "Error: No artifact IDs provided."
+            echo "Help: Check the calling workflow's inputs.artifact_ids parameter, usually created by a build workflow."
+            echo "If you recently renamed the build job for the artifacts, without updating the `outputs.artifact_ids` "
+            echo "parameter then this might be the cause of the error."
+            exit 1
+          fi
       - uses: actions/download-artifact@v7
         with:
           artifact-ids: ${{ inputs.artifact_ids }}
