Re-enable actions for the GitHub merge queue

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -34,82 +34,76 @@ env:
   CARGO_TARGET_DIR: C:\\a\\servo\\servo\\target
 
 jobs:
-#  build-win:
-#    name: Windows Build
-#    runs-on: windows-2019
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          fetch-depth: 2
-#      - name: wix311-binaries
-#        shell: powershell
-#        run: |
-#          Start-BitsTransfer -Source https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311-binaries.zip -Destination C:\\wix311-binaries.zip
-#          Expand-Archive C:\\wix311-binaries.zip -DestinationPath C:\\wix
-#          echo "C:\\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
-#      - name: ccache
-#        uses: hendrikmuhs/ccache-action@v1.2
-#      - name: Bootstrap
-#        run: |
-#          python -m pip install --upgrade pip virtualenv
-#          python mach fetch
-#          python mach bootstrap-gstreamer
-#      - name: Release build
-#        run: python mach build --release
-#      - name: Copy resources
-#        run: cp D:\a\servo\servo\resources C:\a\servo\servo -Recurse
-#      - name: Smoketest
-#        run: python mach smoketest --angle
-#      - name: Unit tests
-#        if: ${{ inputs.unit-tests || github.ref_name == 'try-windows' }}
-#        run: python mach test-unit --release
-#      - name: Rename build timing
-#        run: cp C:\a\servo\servo\target\cargo-timings C:\a\servo\servo\target\cargo-timings-windows -Recurse
-#      - name: Archive build timing
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: cargo-timings
-#          # Using a wildcard here ensures that the archive includes the path.
-#          path: C:\\a\\servo\\servo\\target\\cargo-timings-*
-#      - name: Package
-#        run: python mach package --release
-#      - name: Upload Package
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: win
-#          # These files are available
-#          # MSI Installer: C:\a\servo\servo\target\release\msi\Installer.msi
-#          # Bundle: C:\a\servo\servo\target\release\msi\Servo.exe
-#          # Zip: C:\a\servo\servo\target\release\msi\Servo.zip
-#          path: C:\\a\\servo\\servo\\target/release/msi/Servo.exe
-#      - name: Upload
-#        if: ${{ inputs.upload }}
-#        run: |
-#          python mach upload-nightly win --secret-from-environment `
-#            --github-release-id ${{ inputs.github-release-id }}
-#        env:
-#          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
-#          NIGHTLY_REPO_TOKEN: ${{ secrets.NIGHTLY_REPO_TOKEN }}
-#          NIGHTLY_REPO: ${{ github.repository_owner }}/servo-nightly-builds
-#
-#  build_result:
-#    name: Windows Workflow
-#    runs-on: ubuntu-latest
-#    if: always()
-#    # needs all build to detect cancellation
-#    needs:
-#      - "build-win"
-#
-#    steps:
-#      - name: Mark the job as successful
-#        run: exit 0
-#        if: ${{ !contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') }}
-#      - name: Mark the job as unsuccessful
-#        run: exit 1
-#        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
-  build_result:
+  build:
+    name: Build
+    runs-on: windows-2019
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 2
+      - name: wix311-binaries
+        shell: powershell
+        run: |
+          Start-BitsTransfer -Source https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311-binaries.zip -Destination C:\\wix311-binaries.zip
+          Expand-Archive C:\\wix311-binaries.zip -DestinationPath C:\\wix
+          echo "C:\\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+      - name: ccache
+        uses: hendrikmuhs/ccache-action@v1.2
+      - name: Bootstrap
+        run: |
+          python -m pip install --upgrade pip virtualenv
+          python mach fetch
+          python mach bootstrap-gstreamer
+      - name: Release build
+        run: python mach build --release
+      - name: Copy resources
+        run: cp D:\a\servo\servo\resources C:\a\servo\servo -Recurse
+      - name: Smoketest
+        run: python mach smoketest --angle
+      - name: Unit tests
+        if: ${{ inputs.unit-tests || github.ref_name == 'try-windows' }}
+        run: python mach test-unit --release
+      - name: Rename build timing
+        run: cp C:\a\servo\servo\target\cargo-timings C:\a\servo\servo\target\cargo-timings-windows -Recurse
+      - name: Archive build timing
+        uses: actions/upload-artifact@v3
+        with:
+          name: cargo-timings
+          # Using a wildcard here ensures that the archive includes the path.
+          path: C:\\a\\servo\\servo\\target\\cargo-timings-*
+      - name: Package
+        run: python mach package --release
+      - name: Upload package
+        uses: actions/upload-artifact@v3
+        with:
+          name: win
+          # These files are available
+          # MSI Installer: C:\a\servo\servo\target\release\msi\Installer.msi
+          # Bundle: C:\a\servo\servo\target\release\msi\Servo.exe
+          # Zip: C:\a\servo\servo\target\release\msi\Servo.zip
+          path: C:\\a\\servo\\servo\\target/release/msi/Servo.exe
+      - name: Upload nightly
+        if: ${{ inputs.upload }}
+        run: |
+          python mach upload-nightly win --secret-from-environment `
+            --github-release-id ${{ inputs.github-release-id }}
+        env:
+          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
+          NIGHTLY_REPO_TOKEN: ${{ secrets.NIGHTLY_REPO_TOKEN }}
+          NIGHTLY_REPO: ${{ github.repository_owner }}/servo-nightly-builds
+
+  result:
     name: Result
     runs-on: ubuntu-latest
+    if: always()
+    # needs all build to detect cancellation
+    needs:
+      - "build"
+
     steps:
-      - name: Print workflow inputs
-        run: echo unit='${{ inputs.unit-tests }}' wpt='${{ inputs.wpt }}' layout='${{ inputs.layout }}'
+      - name: Mark the job as successful
+        run: exit 0
+        if: ${{ !contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') }}
+      - name: Mark the job as unsuccessful
+        run: exit 1
+#        if: contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled')
